name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature
      placeholder: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: Describe the problem you're trying to solve
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like to see this implemented?
      placeholder: Describe your proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches have you considered?
    validations:
      required: false
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: How would you use this feature?
      placeholder: Describe your specific use case
    validations:
      required: false
